#ifndef LEDCFG_H_
#define LEDCFG_H_

#define LED0_DDR DDRA
#define LED1_DDR DDRA
#define LED2_DDR DDRA
#define LED3_DDR DDRA
#define LED4_DDR DDRA

#define LED0_PORT PORTA
#define LED1_PORT PORTA
#define LED2_PORT PORTA
#define LED3_PORT PORTA
#define LED4_PORT PORTA

#define LED0_PIN_VALUE PA0
#define LED1_PIN_VALUE PA1
#define LED2_PIN_VALUE PA2
#define LED3_PIN_VALUE PA3
#define LED4_PIN_VALUE PA4
#define LED_COUNT 5


#endif /* LEDCFG_H_ */
