#ifndef BUTTONCFG_H_
#define BUTTONCFG_H_


#define PORT_DIRECTION_BUTTON DDRD
#define PORT_BUTTON PORTD
#define PIN_BUTTON PIND
#define PIN_BUTTON_POWER PD0
#define PIN_BUTTON_NEXT PD1
#define PIN_BUTTON_NEXT_DIGIT PD2
#define PIN_BUTTON_INCREASE PD3
#define PIN_BUTTON_DECREASE PD4
#define PIN_BUTTON_OK PD5
#define PIN_BUTTON_EDIT PD6
#define BUTTON_COUNT 7

#define MAX_COUNTER_VALUE 100
#define BUTTON_TIMER_MS 1
#define BUTTON_TIMER_HELD_MS 1000

#endif /* BUTTONCFG_H_ */