#ifndef BUTTONCFG_H_
#define BUTTONCFG_H_


#define BUTTON0_DDR DDRD
#define BUTTON1_DDR DDRD
#define BUTTON2_DDR DDRD
#define BUTTON3_DDR DDRD
#define BUTTON4_DDR DDRD
#define BUTTON5_DDR DDRD
#define BUTTON7_DDR DDRD

#define BUTTON0_PORT PORTD
#define BUTTON1_PORT PORTD
#define BUTTON2_PORT PORTD
#define BUTTON3_PORT PORTD
#define BUTTON4_PORT PORTD
#define BUTTON5_PORT PORTD
#define BUTTON7_PORT PORTD

#define BUTTON0_PIN PIND
#define BUTTON1_PIN PIND
#define BUTTON2_PIN PIND
#define BUTTON3_PIN PIND
#define BUTTON4_PIN PIND
#define BUTTON5_PIN PIND
#define BUTTON7_PIN PIND

#define BUTTON0_PIN_VALUE PD0
#define BUTTON1_PIN_VALUE PD1
#define BUTTON2_PIN_VALUE PD2
#define BUTTON3_PIN_VALUE PD3
#define BUTTON4_PIN_VALUE PD4
#define BUTTON5_PIN_VALUE PD5
#define BUTTON7_PIN_VALUE PD6

#define BUTTON_COUNT 7

#define MAX_COUNTER_VALUE 100
#define BUTTON_TIMER_MS 1
#define BUTTON_TIMER_HELD_MS 1000


#endif /* BUTTONCFG_H_ */
